[phases.setup]
nixPkgs = ["nodejs", "yarn", "postgresql"]

[phases.install]
cmds = [
  "yarn install --frozen-lockfile"
]

[phases.build]
cmds = [
  "yarn build",
  "cp -r .next/static .next/standalone/.next/" # ensure static assets available
]

[phases.release]
cmds = [
  "npx @better-auth/cli migrate" # run migrations once before starting app
]

[start]
cmd = "node .next/standalone/server.js"
