[phases.setup]
commands = ["echo 'setup'"]

[phases.build]
commands = [
  "npm ci",
  "npm run build"
]

[phases.start]
commands = [
  # run migrations first (non-interactive)
  "npm run migrate",
  # then start your production server (change if you use standalone)
  "node .next/standalone/server.js"
]
